@plr = player()


@hero = associative_array(
            'name': '§0W&ea&0s&ep',
            'class': 'wasp',
            'sig': 'KSoh3cCLBPdy/wN54r9M10HCTDUvqd2BfE5O0zH2PM8sjALoeFG7bVqiSxp9GRyCF7Ut4gDckFhw4eF9JC5fkRh43QfEtB9pwqEk7ppbjP3RwUrkS4iLEbAUgk5ebovtAyYjYTjU/WGWm6X2/7mBH8E9KIeQt8lJ+1l12cHJ76GhVxVW+6/Ion3TkuetrWK7+hCDrxM5EMTIqEZcfHufYVARMQELbMbJZkvp3TJ2sNwfHszRWiDY2mXuRD2FU8YJKdw57xLnvEjhXlBLSydTKjNAWgbNLZQvQz2dp6Wd9Qu0sVOK6I94dgl8q86whgBqMCRnN53uBBpatt/OmVhxQjfviM+TeRdpIA8FhLwr6z6avmZdCOl8p2xg+ptE5AlyUHv5bmB7kxNXE/c80FEgaR1DHwMPBiKbHvYFWiIX4wqJNZknfOEKCfMUZYHkQB2acgAG4MMgzrmkh5czwHKNx907UDhFOa7jGBQYXq6PF+Y9y3AloWPUSXO9pEHWFOQ7//gCXsMjC4AJvvhCapnVzcNI/SnrQjM44NnsF33VcfyAdAxWpq4DhJ3mR1Az0cvMp0xZmnzOJ88hB49LtaSXNud4+FB+fqS3Z3u7kpVOeCwEL8z9sjQF6zaVHe9eQeYyZ50n21h9TPDnc2LhyIGOoWFPPt9+VayHy3xHXTgP7dc=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODQ3NTUxNzUyMjYsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsibWV0YWRhdGEiOnsibW9kZWwiOiJzbGltIn0sInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWNhODZlMzAxOTJhODQzZjVjZjdjNGRjNTE4YjdhOTY0YmFjNGVhNWEyODhmMzhlY2NlMjcwOGZlOWZjOWMifX19',
            'trail': '',
            'op': 'false',
            'speech': "Feel my sting!",
            'powers': array(
                "/buff",
                "/jump 0-7",
                "/run 0-4",
                "/haste 0-2",
                "/carryplayer",
                "/dismountplayer",
                "/normalsize",
                "/grow",
                "/fly",
                "/flyspeed 0-8"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 10 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 21 9999 4 true",
                "/disguiseplayer ". @plr ." villager baby",
                
            )
)
