@plr = player()


@hero = associative_array(
            'name': '§4W§co§4n§cd§4e§cr §0M§8a§7n',
            'class': 'wonderman',
            'sig': 'Gw9jtMBe0XuOGvry/nubkhnxVEGpuJtt9UNPj1LZeuoXRLy8WO8ivIMnu0FFSVXJH+G4jzmORg7FG5Vuc+n3ojMV117uUpuDCL1xVID5rjamU9dtWVlClXHpt3hV3Von60mKT6fHEg1W1D5FIkXiKPHkfmlJ7LDZzaTB+/EJ63ip6ZEAGlVZxbSEVnkHeO4o2VDjtaEgoe+EWQlGsCbteqayMVgLNGRslDPrzwEs3pxAJ8DPJJOMJyYJRroXuRGynG+U6NpK07n5+pJbaO1UrOFV10yDhTJR3FnQySZDyZK17bl8X3WaTqUq2d74UUKisazWUHephdAUOrLZT3fchF2IBsLkixkuTU/M1wcn/7s6wgflzqbnHu4WfK+5YyUMVAfDRUx/4eRzvxbPXklAc2/8qJgWjuqTZhxB4Z+9anTd1n0IX4lyaUCG/qxHG3G6AxkfBMQY6buzCVN6CujOq0P4XvhOCvsG8R2wCXruBtGMix9TAkyvQ9w+G1OAvRT5pJeUgx/rvN0DL3gVa6+gue+yWsP1tq3wl5St0Y900RaAibVEGwl0LvxP/5397psMY11sPANaAM47fefnTMOSwh+s2ABZhjrG9IClkaM40INVKRQeQfKR468LZGk7elrbBbTr7GkBcYnbEQLQie0qffm39XH/PgOKbR8zUlgaqgY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODYzMjExMDU1MTYsInByb2ZpbGVJZCI6IjI4YmM1NTllZjZiYzQxZDVhOWE4NGIxNzZiMGM2ZDBhIiwicHJvZmlsZU5hbWUiOiJNaXN0b2ZmZWxlczAxIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am full of ionic energy!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/jump 0-9",
                "/run 0-9",
                "/haste 0-9",
                "/flyspeed <number>",
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 20 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 13 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&4S&ep&4e&ce&ed&8s&0t&9e&1r_&4Boots"                
            )
)
